[package]
name = "test_ci"
version = "0.1.0"
edition = "2021"
authors = ["liulu17 1085554719@qq.com"]
description = "test for crate publish"
publish = true
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
